// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqTm-EorvzNUjdpA2Sxp7iibHIT9-mAk',
    appId: '1:706042149840:web:966f9d0858d0dd7cfa57d5',
    messagingSenderId: '706042149840',
    projectId: 'mind-ur',
    authDomain: 'mind-ur.firebaseapp.com',
    storageBucket: 'mind-ur.firebasestorage.app',
    measurementId: 'G-WX4D3CK5SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gowSCG6FpXT3u3hfZHEp0k45q3Dx7sE',
    appId: '1:706042149840:android:f247d1f596ffce37fa57d5',
    messagingSenderId: '706042149840',
    projectId: 'mind-ur',
    storageBucket: 'mind-ur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43IHcaOZ5bpPNP1HER-uYPRpVSE4r1xw',
    appId: '1:706042149840:ios:5d6676b71decd9f7fa57d5',
    messagingSenderId: '706042149840',
    projectId: 'mind-ur',
    storageBucket: 'mind-ur.firebasestorage.app',
    iosBundleId: 'com.amit.mindur',
  );
}
